version: "3.9"

services:
  angular-app:
    build:
      context: ../..     
      dockerfile: config/docker/Dockerfile
    container_name: neos-template
    ports:
      - "8080:80" 
    restart: unless-stopped
    environment:
      - NODE_ENV=development
